### ISSUE TITLE
Sticky subjects are not highlited enough

### ISSUE THREAD

**Issue by kocio-pl** [natrius/air3#4]
In the current style sticky subjects have both solid color and an asterisk in the name, while Air3 uses only text string there in paler shade of blue. I think it would be better to follow current scheme for them.

**Comment by Luzandro** [comment]
As far as I can see sticky subjects look exactly the same in Air and Air3 and I can't see any asterisk?

**Comment by natrius** [comment]
Luzandro is correct, that was something a mod had changed when he put the thread to sticky, i guess. It is now the same as before when sticky. I will take a look if i can do anything to make it better visible.

**Comment by natrius** [comment]
Ideas on how to make it better visible? 

- another icon
- bigger font size
- Add custom symbols (not possible for me, will ask in the FluxBB community)

First and second could be achieved i guess. 

EDIT: Increased the fontsize of the `sticky` for now, i like it so far.

**Comment by natrius** [comment]
I was actually able to add an `▼` in front via css. Could add it behind as well. 

![grafik](https://user-images.githubusercontent.com/7243447/62573057-6f646880-b895-11e9-8e3a-9629403b2605.png)
